### ISSUE TITLE
Server hangs during termination

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#691]
### Describe the problem you're observing
The server is failing to terminate properly/completely after running an example application (i.e., when inode cleanup is needed).
It appears to be hanging/deadlocking, even when there is only a single server and client.

First noticed when running CI tests (4 nodes, 2 ppn).
The `process_is_not_running()` test checks if `unifyfsd` is still running after `unifyfs terminate` is run.
It still is, even after increasing the timeout to `process_is_not_running()` by minutes to give more time for the terminate command to finish:
```
ok 116 - unifyfsd is still running
not ok 117 - unifyfsd has stopped
#	
#	    process_is_not_running unifyfsd 10
#	
not ok 118 - verify unifyfsd has stopped
#	
#	    test_must_fail process_is_running unifyfsd 10
#	
ok 119 # skip Verify UNIFYFS_MOUNTPOINT (/unifyfs) is empty (missing REAL_MP)
ok 120 # skip Cleanup UNIFYFS_CI_POSIX_MP:  (missing POSIX)
ok 121 - Cleanup hosts
All done @ Thu Sep 16 19:08:05 UTC 2021
Total run time -- 00:22:30
# failed 2 among 121 test(s)
1..121
```

Testing on my own I'm able to replicate this problem on 1 node with 1 ppn.

Tests started failing somewhere between commits a58838e7763c5e243af5a7f2612d80596ace7a39 and 178dfd5b71a8e3c9119cf1a42dddc60b94de4c16.

### Describe how to reproduce the problem
On a single node allocation start the server, run an example application, and then stop the server:
``` bash
# start server
$UNIFYFS_INSTALL/bin/unifyfs start -d -S $UNIFYFS_SHAREDFS_DIR -e $UNIFYFS_INSTALL/bin/unifyfsd &> $UNIFYFS_LOG_DIR/unifyfs.start.out

# run example
jsrun -r 1 -n 1 -a 1 -c 18 -e individual -k $UNIFYFS_LOG_DIR/writeread-gotcha.err -o $UNIFYFS_LOG_DIR/writeread-gotcha.out $UNIFYFS_EXAMPLES/writeread-gotcha -f writeread-gotcha.app -k -v

# stop server
$UNIFYFS_INSTALL/bin/unifyfs terminate -d &> $UNIFYFS_LOG_DIR/unifyfs.terminate.out
```

Checking to see if the server is still running at this point shows that it is:
``` bash
[prompt]$ jsrun -r1 -n1 pidof unifyfsd
24785
```

### Include any warning or errors or releveant debugging data
The server log shows the exit request, followed by a plethora of `unifyfs_logio_free()` calls, and a `signal_new_requests()` call at the end:
```
2021-09-17T09:37:48 tid=24785 @ exit_request() [unifyfs_server.c:147] exit requested
2021-09-17T09:37:48 tid=24785 @ main() [unifyfs_server.c:469] starting service shutdown
2021-09-17T09:37:48 tid=24785 @ unifyfs_logio_free() [../../common/src/unifyfs_logio.c:740] log_off=0, nbytes=1048576 : mem_sz=1048576 spill_sz=0 spill_off=0
2021-09-17T09:37:48 tid=24785 @ unifyfs_logio_free() [../../common/src/unifyfs_logio.c:740] log_off=4194304, nbytes=1048576 : mem_sz=1048576 spill_sz=0 spill_off=0
...
2021-09-17T09:37:48 tid=24785 @ unifyfs_logio_free() [../../common/src/unifyfs_logio.c:740] log_off=2139095040, nbytes=1048576 : mem_sz=0 spill_sz=1048576 spill_off=1874853888
2021-09-17T09:37:48 tid=24785 @ unifyfs_logio_free() [../../common/src/unifyfs_logio.c:740] log_off=2143289344, nbytes=1048576 : mem_sz=0 spill_sz=1048576 spill_off=1879048192
2021-09-17T09:37:48 tid=24785 @ signal_new_requests() [unifyfs_request_manager.c:267] signaling new requests
```

Using `gdb` or `gstack` on the server pid shows:
```
[prompt]$ gdb -p 24785
#0  0x00002000006f2d34 in __lll_lock_wait (futex=0x200, private=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/lowlevellock.c:49
#1  0x00002000006ef20c in __pthread_cond_signal (cond=0x20001c001740) at pthread_cond_signal.c:40
#2  0x0000000010047cd0 in signal_new_requests (reqmgr=0x20001c001730) at ../../../server/src/unifyfs_request_manager.c:268
#3  0x000000001004a338 in rm_submit_client_callback_request (req=0x103b32c0) at ../../../server/src/unifyfs_request_manager.c:846
#4  0x000000001003a010 in unifyfs_inode_destroy (ino=0x200020001070) at ../../../server/src/unifyfs_inode.c:207
#5  0x000000001003dc70 in unifyfs_inode_tree_clear (tree=0x10081d90 <_global_inode_tree>) at ../../../server/src/unifyfs_inode_tree.c:192
#6  0x000000001003d938 in unifyfs_inode_tree_destroy (tree=0x10081d90 <_global_inode_tree>) at ../../../server/src/unifyfs_inode_tree.c:69
#7  0x0000000010050f90 in main (argc=9, argv=0x7fffffff7c98) at ../../../server/src/unifyfs_server.c:475
```
**Note:** All four server logs and stack traces from the CI tests look like this as well.

`unifyfs_inode_destroy()` calls `unifyfs_logio_free()` 512 times (same number of `unifyfs_logio_write()` calls from client application):
https://github.com/LLNL/UnifyFS/blob/178dfd5b71a8e3c9119cf1a42dddc60b94de4c16/server/src/unifyfs_inode.c#L162

whereafter it gets to `rm_submit_client_callback_request()` which is where the `signal_new_requests()` call at the end of the log comes from:
https://github.com/LLNL/UnifyFS/blob/178dfd5b71a8e3c9119cf1a42dddc60b94de4c16/server/src/unifyfs_request_manager.c#L846

**Comment by CamStan** [comment]
Resolved by #721
